---
format: 
  revealjs:
    slide-number: true
    code-link: true
    highlight-style: a11y
    chalkboard: true
    theme: 
      - meds-slides-styles.scss
engine: knitr
execute:
  eval: true
---

## {#title-slide data-menu-title="Title Slide" background="#053660"} 

```{r}
#| eval: true
#| echo: false
today <- format(Sys.time(), "%b %d, %Y")
```

[Teach Me How to Google 2.0]{.custom-title}

[*The case for search & debugging skills in the age of AI*]{.custom-subtitle2}

:::: {.columns}

::: {.column width="50%"}
[**Published:** July 1, 2025]{.body-text-s .baby-blue-text}
:::

::: {.column width="50%"}
[**Last updated:** `r today`]{.body-text-s .baby-blue-text}
:::

::::

<hr class="hr-teal">

:::: {.columns} 

::: {.column width="50%"}
[Sam Shanny-Csik |]{.custom-subtitle2}<br>
[*Lecturer & Data Training Coordinator*]{.custom-subtitle3}
:::

::: {.column width="50%"}
[Master of Environmental Data Science |]{.custom-subtitle2}<br>
[*Bren School of Environmental Science & Management*]{.custom-subtitle3}
:::

::::

<br>

::: {.title-footer}
Slides & source code available on [GitHub {{< fa brands github title="GitHub Octocat logo" >}}](https://github.com/UCSB-MEDS/teach-me-how-to-google-2.0)
:::

---

original [Teach Me How to Google](https://ucsb-meds.github.io/teach-me-how-to-google/#1) developed in Fall 2021 (a very different world!)

---

- Address the elephant in the room (ChatGPT / GenAI)
  - it's everywhere and for a lot of us, it's the first place we might turn to for answers
  - even Google provides an AI summary at the very top of the page
  - so, does it even pay to "Google" in the traditional sense anymore?

- Argue, YES!

---

I asked ChatGPT what it would tell new data science students about the importance and utility of using Google vs. ChatGPT (or related GenAI tools) in the early stages of a learning journey. It's response:

"Think of Google as your first stop for researching and understanding the problem, and GenAI as a helpful assistant for brainstorming or clarifying once you know what you’re asking."

---

Erosion of critical thinking skills from overreliance on ChatGPT

- MIT study (June 2025 [preprint](https://arxiv.org/pdf/2506.08872v1) & [summary article by Time](https://time.com/7295195/ai-chatgpt-google-learning-school/))

- divided subjects into 3 groups and asked them to write multiple SAT-style essays over the course of several months
  - group 1: could use ChatGPT
  - group 2: could use Google Searches
  - group 3: only their brains!

- Group 1: lowest brain engagement, delivered similar "souless" esssays that lacked original thought; by 3rd essay, largely copy/pasting 
- Group 3: highest neural connectivity especially in bands associated with "creativity ideation, memory load, and semantic processing"; more engaged/curious, claimed ownership, expressed higher satisfaction with their essasys
- Group 2: also high levels of satisfaction and brain activity

. . .

After 3 essays, they were asked to re-write one of their previous efforts. BUT group 1 couldn't use tool, while group 3 could. Group 1 "remembered little of their own essays, and showed weaker alpha and theta brain waves, which likely reflected a bypassing of deep memory processes" (don't integrate into your memory networks). 

"The second group, in contrast, performed well, exhibiting a significant increase in brain connectivity across all EEG frequency bands. This gives rise to the hope that AI, if used properly, could enhance learning as opposed to diminishing it."

---

Our approach: 

Summer / Fall: developing core programming competencies (workflows, patterns, syntax, vocabulary, documentation)

Winter / Spring: leveraging GenAI tools to increase problem-solving efficiency (includes workshops, intentionally integrating GenAI into course curricula)

You're here because you want to learn! ChatGPT (and related tools) will certainly become a part of your workflow, but in this early stage of MEDS, we want you to focus on core competencies, understanding how to properly use tools, write code, and troubleshoot problems. To do that most effectively, you need to commit to active learning processes and approaches. 

---

Googling...

1. Teaches you how to read documentation and official sources
  - documentation is like a cookbook for code -- Imagine trying to cook a new dish without ever looking at the recipe. You might get something edible by copying what someone else does, but you won’t know why you’re doing each step, what ingredients you can substitute, or how to adjust it to your taste.
2. Exposes you to different solutions and perspectives
  - seeing many approaches helps us understand not only *what* works, but *why* it works
3. Build your debugging and search skills, including expanding your vocabulary!
  - it's difficult to craft effective queries without exposure to vocab, primary sources, documentation, 
4. Promotes critical thinking
  - evaluate source credibility, compare solutions, decide what fits *your* use case; GenAI often gives one 
5. Tempers overreliance on black-box answers
  - e.g. ChatGPT can hallucinate or offer solutions that simply don't work (or worse, cause serious downstream problems); online searches often return code vetted by other uses
6. Show real-world probelm solving patterns
7. Encourages community learning 
  - Googling can take you to community forums, blog posts, etc. Seeing how people ask and respond to questions is important
8. Seek help with version-specific issues
  - GenAI sometimes suggest outdated solutions
9. Develop resilience!
  - rarely will you get to a perfect answer on your first try when troublshooting complex problems (even when using GenAI)

---

<!-- From Kat: 
- students know what to ask, they don't know how to implent ChatGPT's answers
- give them a completely out of their toolbox problem to solve
- important foundational knowledge to not fuck up their computer -->
- guardrails for safe troubleshooting
- don't delete config files / don't delete things

---

From Albert Rapp's 7/2 newsletter:

“Why should I even bother learning this stuff when AI can just do it faster than I can?”
And to that, I’d say:
Yes, AI is great. I use it every day to help with my coding. But no, you can’t skip learning the fundamentals if you want to become a proficient data scientist.
Sure, you can get a quick fix for a task using ChatGPT. But the problem with that is, when you operate like that, you never actually learn how to do the thing yourself. And when
you’re supposed to be the person who can handle data quickly and reliably but
all you can do is describe what you think you need to an AI and
you have to hope it gives the right result,
then you’re setting yourself up for failure.
Even worse, you’re also setting yourself up for a lot of frustration. You know, the kind of frustration you will feel after getting the 10th incorrect answer starting with “Yes, you’re absolutely right. Here’s the fixed code:”
Been there, done that (with programming languages I have only scratched the surface of).
That’s why (no matter how good this stochastic parrot gets in the future) you’ll always be better off when you’ve taken the time to understand battle-tested techniques to crunch data.
And a modern data scientist uses AI, of course. But the usage is much more effective when you have the skill set to ask targeted questions and spot AI mistakes quickly.

---

<!-- ChatGPT will post knowledge from Stack Overflow directly into responses. The OpenAI chatbot will provide attribution to the Stack Overflow source, guiding users to the relevant source. [ChatGPT Partners With Stack Overflow, Enhancing Access to Coding Data](https://aibusiness.com/nlp/chatgpt-partners-with-stack-overflow-enhancing-access-to-coding-data#close-modal) (May 9, 2024)
 -->





<!-- ---

Some things you may have already heard: 

- CHatGPT has biases (cite)
- It can halucinate / make stuff up (cite)

. . . 

It *is* continually getting better (cite study about how much it's improved since 2022?)

---

Environmental impacts
- energy demands
- water for cooling hardware
- raw material mining for GPU fabrication

[Explained: Generative AI’s environmental impact](https://news.mit.edu/2025/explained-generative-ai-environmental-impact-0117) (Jan 17, 2025)

But also, GenAI is poised to help us solve environmental problems at a much faster pace than ever before. 

Remains to be seen if benefits outweigh risks. -->